-- ============================================================================
-- pit_penalties — pit-road penalty calls parsed from NASCAR race-control
-- lap notes (cf.nascar.com cacher/{year}/{series_id}/{race_id}/lap-notes.json,
-- verified live 2026-07-23; archived like the pit feed).
-- Style follows pit_stops. RLS public read + insert/delete for the Python
-- loader's delete-then-insert (task #64 tightens before go-live).
--
-- category = the differentiator: 'driver' (speeding, commitment, outside box)
-- vs 'crew' (over the wall too soon, uncontrolled tire, too many men, fueling)
-- vs 'other' (penalty-flavored but unclassified — raw kept for audit).
-- ============================================================================

create table if not exists pit_penalties (
  id              bigint generated by default as identity primary key,
  race_id         int8 references races(id),
  nascar_race_id  int4,
  series          text not null,
  year            int4 not null,
  track_name      text not null,   -- canonical, copied from races registry
  race_number     int4 not null,   -- SEASON round = races.race_number
  lap             int4,
  flag_state      int2,
  car_number      text not null,
  penalty_text    text not null,
  category        text not null,   -- 'driver' | 'crew' | 'other'
  note_id         int4,
  raw_note        text,            -- full original note sentence context (audit)
  created_at      timestamptz default now()
);

create unique index if not exists pit_penalties_unique
  on pit_penalties (race_id, lap, car_number, penalty_text);

create index if not exists pit_penalties_race_idx on pit_penalties (race_id);
create index if not exists pit_penalties_crew_idx on pit_penalties (series, year, car_number, category);

alter table pit_penalties enable row level security;

drop policy if exists "pit_penalties public read"   on pit_penalties;
drop policy if exists "pit_penalties public insert" on pit_penalties;
drop policy if exists "pit_penalties public delete" on pit_penalties;

create policy "pit_penalties public read"   on pit_penalties for select using (true);
create policy "pit_penalties public insert" on pit_penalties for insert with check (true);
create policy "pit_penalties public delete" on pit_penalties for delete using (true);
