-- ============================================================================
-- pit_stops — raw NASCAR per-stop pit telemetry (source: cf.nascar.com
-- cacher/live/series_{s}/{race}/live-pit-data.json, verified populated 2018+)
-- Added 2026-07-18. Style follows existing tables; RLS public read like
-- odds_snapshots (+ insert/delete for the Python loader's delete-then-insert;
-- tighten under task #83 before go-live).
--
-- DESIGN NOTES (domain rules from pitboard.md / pit brief):
--   * Rows are RAW telemetry. No cross-series pooling; analysis is
--     within-series, within-season (cup 4-tire ~9-10s, trucks/oreilly 13-15s).
--   * race_id FK -> races.id is the canonical join anchor; series/year/
--     track_name/race_number are denormalized copies FROM the races registry
--     (canonical tracks.name + SEASON round), so they always agree with it.
--     Backfill is DRIVEN from the races table, which already excludes
--     exhibitions and enforces the 2022 era floor.
--   * CREW KEY = (car_number, organization, year[season], series).
--     driver_name is for joining to results only. organization = weekend-feed
--     team_name (crews belong to the car/team, not the driver).
--   * flag_state = pit_in_flag_status (1 green, 2 yellow, 8 warm-up...).
--     green_flag stops are the skill signal. Pre-race/warm-up rows are KEPT
--     raw (filter flag_state = 1 and lap > 0 in analysis).
--   * Sentinels sanitized at load: NASCAR uses -1 (and 0 for prev/next lap
--     time) for not-populated -> stored as NULL, so medians are never
--     poisoned. box_time (pit_stop_duration) NULL = untimed stop.
--   * Target metric later (do not compute here): median green-flag 4-tire
--     box_time per car per season + consistency. Schema supports it:
--     series + year + car_number + organization + tires_changed + flag_state
--     + box_time.
--   * Idempotency: loader does delete-by-race_id then insert; the unique
--     index is the backstop against double-loads.
-- ============================================================================

create table if not exists pit_stops (
  id                    bigint generated by default as identity primary key,
  race_id               int8 references races(id),
  nascar_race_id        int4,           -- cf.nascar.com race id (provenance)
  series                text not null,  -- 'cup' | 'oreilly' | 'trucks'
  year                  int4 not null,
  track_name            text not null,  -- canonical tracks.name (copied from races)
  race_number           int4 not null,  -- SEASON round = races.race_number
  car_number            text not null,  -- text, matches loop_data.car_number
  driver_name           text,
  nascar_driver_id      int4,
  organization          text,           -- weekend-feed team_name (crew key part)
  crew_chief            text,
  manufacturer          text,
  pit_box               int4,
  lap                   int4,           -- vehicle lap_count at pit entry
  leader_lap            int4,
  flag_state            int2,           -- pit_in_flag_status (1=green, 2=yellow, 8=warmup)
  flag_state_out        int2,           -- pit_out_flag_status
  green_flag            boolean,        -- flag_state = 1 (loader-set convenience)
  pit_stop_type         text,           -- FOUR_WHEEL_CHANGE / TWO_WHEEL_CHANGE_* / OTHER
  tires_changed         int2,           -- 0/2/4 derived from the four booleans
  lf                    boolean,
  lr                    boolean,
  rf                    boolean,
  rr                    boolean,
  box_time              numeric,        -- pit_stop_duration (secs; NULL = untimed)
  pit_road_time         numeric,        -- total_duration (in + box + out)
  in_travel             numeric,
  out_travel            numeric,
  pit_in_race_time      numeric,
  pit_out_race_time     numeric,
  pit_in_rank           int2,
  pit_out_rank          int2,
  positions_gained_lost int2,
  prev_lap_time         numeric,        -- NULL pre-2022-ish (feed stores 0)
  next_lap_time         numeric,
  created_at            timestamptz default now()
);

-- backstop against accidental double-load (loader deletes by race_id first).
-- pit_in_race_time is in the key because a car CAN pit twice on the same lap.
create unique index if not exists pit_stops_stop_unique
  on pit_stops (series, year, race_number, car_number, lap,
                (coalesce(pit_in_race_time, -1)));

create index if not exists pit_stops_race_idx on pit_stops (race_id);
create index if not exists pit_stops_crew_idx on pit_stops (series, year, car_number);
create index if not exists pit_stops_org_idx  on pit_stops (series, year, organization);

-- RLS: public read (like odds_snapshots) + insert/delete so the Python
-- backfill's delete-then-insert works through the publishable key.
-- Task #83 (tighten RLS before go-live) applies to these two write policies.
alter table pit_stops enable row level security;

drop policy if exists "pit_stops public read"   on pit_stops;
drop policy if exists "pit_stops public insert" on pit_stops;
drop policy if exists "pit_stops public delete" on pit_stops;

create policy "pit_stops public read"   on pit_stops for select using (true);
create policy "pit_stops public insert" on pit_stops for insert with check (true);
create policy "pit_stops public delete" on pit_stops for delete using (true);
